// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.ufpb.dce.bloomer.core.model;

import br.ufpb.dce.bloomer.core.model.Jogo;
import br.ufpb.dce.bloomer.core.model.JogoDataOnDemand;
import br.ufpb.dce.bloomer.core.model.JogoIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect JogoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: JogoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: JogoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: JogoIntegrationTest: @Transactional;
    
    @Autowired
    private JogoDataOnDemand JogoIntegrationTest.dod;
    
    @Test
    public void JogoIntegrationTest.testCountJogoes() {
        Assert.assertNotNull("Data on demand for 'Jogo' failed to initialize correctly", dod.getRandomJogo());
        long count = Jogo.countJogoes();
        Assert.assertTrue("Counter for 'Jogo' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void JogoIntegrationTest.testFindJogo() {
        Jogo obj = dod.getRandomJogo();
        Assert.assertNotNull("Data on demand for 'Jogo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Jogo' failed to provide an identifier", id);
        obj = Jogo.findJogo(id);
        Assert.assertNotNull("Find method for 'Jogo' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Jogo' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void JogoIntegrationTest.testFindAllJogoes() {
        Assert.assertNotNull("Data on demand for 'Jogo' failed to initialize correctly", dod.getRandomJogo());
        long count = Jogo.countJogoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Jogo', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Jogo> result = Jogo.findAllJogoes();
        Assert.assertNotNull("Find all method for 'Jogo' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Jogo' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void JogoIntegrationTest.testFindJogoEntries() {
        Assert.assertNotNull("Data on demand for 'Jogo' failed to initialize correctly", dod.getRandomJogo());
        long count = Jogo.countJogoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Jogo> result = Jogo.findJogoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Jogo' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Jogo' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void JogoIntegrationTest.testFlush() {
        Jogo obj = dod.getRandomJogo();
        Assert.assertNotNull("Data on demand for 'Jogo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Jogo' failed to provide an identifier", id);
        obj = Jogo.findJogo(id);
        Assert.assertNotNull("Find method for 'Jogo' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyJogo(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Jogo' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JogoIntegrationTest.testMergeUpdate() {
        Jogo obj = dod.getRandomJogo();
        Assert.assertNotNull("Data on demand for 'Jogo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Jogo' failed to provide an identifier", id);
        obj = Jogo.findJogo(id);
        boolean modified =  dod.modifyJogo(obj);
        Integer currentVersion = obj.getVersion();
        Jogo merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Jogo' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JogoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Jogo' failed to initialize correctly", dod.getRandomJogo());
        Jogo obj = dod.getNewTransientJogo(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Jogo' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Jogo' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Jogo' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void JogoIntegrationTest.testRemove() {
        Jogo obj = dod.getRandomJogo();
        Assert.assertNotNull("Data on demand for 'Jogo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Jogo' failed to provide an identifier", id);
        obj = Jogo.findJogo(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Jogo' with identifier '" + id + "'", Jogo.findJogo(id));
    }
    
}
