// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.ufpb.dce.bloomer.core.model;

import br.ufpb.dce.bloomer.core.model.Relacao;
import br.ufpb.dce.bloomer.core.model.RelacaoDataOnDemand;
import br.ufpb.dce.bloomer.core.model.RelacaoIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RelacaoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RelacaoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RelacaoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RelacaoIntegrationTest: @Transactional;
    
    @Autowired
    private RelacaoDataOnDemand RelacaoIntegrationTest.dod;
    
    @Test
    public void RelacaoIntegrationTest.testCountRelacaos() {
        Assert.assertNotNull("Data on demand for 'Relacao' failed to initialize correctly", dod.getRandomRelacao());
        long count = Relacao.countRelacaos();
        Assert.assertTrue("Counter for 'Relacao' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RelacaoIntegrationTest.testFindRelacao() {
        Relacao obj = dod.getRandomRelacao();
        Assert.assertNotNull("Data on demand for 'Relacao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Relacao' failed to provide an identifier", id);
        obj = Relacao.findRelacao(id);
        Assert.assertNotNull("Find method for 'Relacao' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Relacao' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RelacaoIntegrationTest.testFindAllRelacaos() {
        Assert.assertNotNull("Data on demand for 'Relacao' failed to initialize correctly", dod.getRandomRelacao());
        long count = Relacao.countRelacaos();
        Assert.assertTrue("Too expensive to perform a find all test for 'Relacao', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Relacao> result = Relacao.findAllRelacaos();
        Assert.assertNotNull("Find all method for 'Relacao' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Relacao' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RelacaoIntegrationTest.testFindRelacaoEntries() {
        Assert.assertNotNull("Data on demand for 'Relacao' failed to initialize correctly", dod.getRandomRelacao());
        long count = Relacao.countRelacaos();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Relacao> result = Relacao.findRelacaoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Relacao' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Relacao' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RelacaoIntegrationTest.testFlush() {
        Relacao obj = dod.getRandomRelacao();
        Assert.assertNotNull("Data on demand for 'Relacao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Relacao' failed to provide an identifier", id);
        obj = Relacao.findRelacao(id);
        Assert.assertNotNull("Find method for 'Relacao' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRelacao(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Relacao' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RelacaoIntegrationTest.testMergeUpdate() {
        Relacao obj = dod.getRandomRelacao();
        Assert.assertNotNull("Data on demand for 'Relacao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Relacao' failed to provide an identifier", id);
        obj = Relacao.findRelacao(id);
        boolean modified =  dod.modifyRelacao(obj);
        Integer currentVersion = obj.getVersion();
        Relacao merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Relacao' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RelacaoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Relacao' failed to initialize correctly", dod.getRandomRelacao());
        Relacao obj = dod.getNewTransientRelacao(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Relacao' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Relacao' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Relacao' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RelacaoIntegrationTest.testRemove() {
        Relacao obj = dod.getRandomRelacao();
        Assert.assertNotNull("Data on demand for 'Relacao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Relacao' failed to provide an identifier", id);
        obj = Relacao.findRelacao(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Relacao' with identifier '" + id + "'", Relacao.findRelacao(id));
    }
    
}
