// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.ufpb.dce.bloomer.core.model;

import br.ufpb.dce.bloomer.core.model.TipoJogoDataOnDemand;
import br.ufpb.dce.bloomer.core.model.TipoQuestao;
import br.ufpb.dce.bloomer.core.model.TipoQuestaoDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect TipoQuestaoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TipoQuestaoDataOnDemand: @Component;
    
    private Random TipoQuestaoDataOnDemand.rnd = new SecureRandom();
    
    private List<TipoQuestao> TipoQuestaoDataOnDemand.data;
    
    @Autowired
    private TipoJogoDataOnDemand TipoQuestaoDataOnDemand.tipoJogoDataOnDemand;
    
    public TipoQuestao TipoQuestaoDataOnDemand.getNewTransientTipoQuestao(int index) {
        TipoQuestao obj = new TipoQuestao();
        setDescricao(obj, index);
        setNome(obj, index);
        return obj;
    }
    
    public void TipoQuestaoDataOnDemand.setDescricao(TipoQuestao obj, int index) {
        String descricao = "descricao_" + index;
        if (descricao.length() > 2000) {
            descricao = descricao.substring(0, 2000);
        }
        obj.setDescricao(descricao);
    }
    
    public void TipoQuestaoDataOnDemand.setNome(TipoQuestao obj, int index) {
        String nome = "nome_" + index;
        if (nome.length() > 100) {
            nome = nome.substring(0, 100);
        }
        obj.setNome(nome);
    }
    
    public TipoQuestao TipoQuestaoDataOnDemand.getSpecificTipoQuestao(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TipoQuestao obj = data.get(index);
        Long id = obj.getId();
        return TipoQuestao.findTipoQuestao(id);
    }
    
    public TipoQuestao TipoQuestaoDataOnDemand.getRandomTipoQuestao() {
        init();
        TipoQuestao obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return TipoQuestao.findTipoQuestao(id);
    }
    
    public boolean TipoQuestaoDataOnDemand.modifyTipoQuestao(TipoQuestao obj) {
        return false;
    }
    
    public void TipoQuestaoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = TipoQuestao.findTipoQuestaoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TipoQuestao' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TipoQuestao>();
        for (int i = 0; i < 10; i++) {
            TipoQuestao obj = getNewTransientTipoQuestao(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
