// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.ufpb.dce.bloomer.core.model;

import br.ufpb.dce.bloomer.core.model.Jogo;
import br.ufpb.dce.bloomer.core.model.JogoDataOnDemand;
import br.ufpb.dce.bloomer.core.model.TipoJogo;
import br.ufpb.dce.bloomer.core.model.TipoJogoDataOnDemand;
import br.ufpb.dce.bloomer.core.model.UsuarioDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect JogoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: JogoDataOnDemand: @Component;
    
    private Random JogoDataOnDemand.rnd = new SecureRandom();
    
    private List<Jogo> JogoDataOnDemand.data;
    
    @Autowired
    private UsuarioDataOnDemand JogoDataOnDemand.usuarioDataOnDemand;
    
    @Autowired
    private TipoJogoDataOnDemand JogoDataOnDemand.tipoJogoDataOnDemand;
    
    public Jogo JogoDataOnDemand.getNewTransientJogo(int index) {
        Jogo obj = new Jogo();
        setNome(obj, index);
        setTipo(obj, index);
        return obj;
    }
    
    public void JogoDataOnDemand.setNome(Jogo obj, int index) {
        String nome = "nome_" + index;
        if (nome.length() > 100) {
            nome = nome.substring(0, 100);
        }
        obj.setNome(nome);
    }
    
    public void JogoDataOnDemand.setTipo(Jogo obj, int index) {
        TipoJogo tipo = tipoJogoDataOnDemand.getRandomTipoJogo();
        obj.setTipo(tipo);
    }
    
    public Jogo JogoDataOnDemand.getSpecificJogo(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Jogo obj = data.get(index);
        Long id = obj.getId();
        return Jogo.findJogo(id);
    }
    
    public Jogo JogoDataOnDemand.getRandomJogo() {
        init();
        Jogo obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Jogo.findJogo(id);
    }
    
    public boolean JogoDataOnDemand.modifyJogo(Jogo obj) {
        return false;
    }
    
    public void JogoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Jogo.findJogoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Jogo' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Jogo>();
        for (int i = 0; i < 10; i++) {
            Jogo obj = getNewTransientJogo(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
