// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.ufpb.dce.bloomer.core.model;

import br.ufpb.dce.bloomer.core.model.Resposta;
import br.ufpb.dce.bloomer.core.model.RespostaDataOnDemand;
import br.ufpb.dce.bloomer.core.model.RespostaIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RespostaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RespostaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RespostaIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RespostaIntegrationTest: @Transactional;
    
    @Autowired
    RespostaDataOnDemand RespostaIntegrationTest.dod;
    
    @Test
    public void RespostaIntegrationTest.testCountRespostas() {
        Assert.assertNotNull("Data on demand for 'Resposta' failed to initialize correctly", dod.getRandomResposta());
        long count = Resposta.countRespostas();
        Assert.assertTrue("Counter for 'Resposta' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RespostaIntegrationTest.testFindResposta() {
        Resposta obj = dod.getRandomResposta();
        Assert.assertNotNull("Data on demand for 'Resposta' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Resposta' failed to provide an identifier", id);
        obj = Resposta.findResposta(id);
        Assert.assertNotNull("Find method for 'Resposta' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Resposta' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RespostaIntegrationTest.testFindAllRespostas() {
        Assert.assertNotNull("Data on demand for 'Resposta' failed to initialize correctly", dod.getRandomResposta());
        long count = Resposta.countRespostas();
        Assert.assertTrue("Too expensive to perform a find all test for 'Resposta', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Resposta> result = Resposta.findAllRespostas();
        Assert.assertNotNull("Find all method for 'Resposta' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Resposta' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RespostaIntegrationTest.testFindRespostaEntries() {
        Assert.assertNotNull("Data on demand for 'Resposta' failed to initialize correctly", dod.getRandomResposta());
        long count = Resposta.countRespostas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Resposta> result = Resposta.findRespostaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Resposta' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Resposta' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RespostaIntegrationTest.testFlush() {
        Resposta obj = dod.getRandomResposta();
        Assert.assertNotNull("Data on demand for 'Resposta' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Resposta' failed to provide an identifier", id);
        obj = Resposta.findResposta(id);
        Assert.assertNotNull("Find method for 'Resposta' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyResposta(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Resposta' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RespostaIntegrationTest.testMergeUpdate() {
        Resposta obj = dod.getRandomResposta();
        Assert.assertNotNull("Data on demand for 'Resposta' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Resposta' failed to provide an identifier", id);
        obj = Resposta.findResposta(id);
        boolean modified =  dod.modifyResposta(obj);
        Integer currentVersion = obj.getVersion();
        Resposta merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Resposta' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RespostaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Resposta' failed to initialize correctly", dod.getRandomResposta());
        Resposta obj = dod.getNewTransientResposta(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Resposta' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Resposta' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Resposta' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RespostaIntegrationTest.testRemove() {
        Resposta obj = dod.getRandomResposta();
        Assert.assertNotNull("Data on demand for 'Resposta' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Resposta' failed to provide an identifier", id);
        obj = Resposta.findResposta(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Resposta' with identifier '" + id + "'", Resposta.findResposta(id));
    }
    
}
