// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.ufpb.dce.bloomer.core.model;

import br.ufpb.dce.bloomer.core.model.TipoQuestao;
import br.ufpb.dce.bloomer.core.model.TipoQuestaoDataOnDemand;
import br.ufpb.dce.bloomer.core.model.TipoQuestaoIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TipoQuestaoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TipoQuestaoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TipoQuestaoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TipoQuestaoIntegrationTest: @Transactional;
    
    @Autowired
    private TipoQuestaoDataOnDemand TipoQuestaoIntegrationTest.dod;
    
    @Test
    public void TipoQuestaoIntegrationTest.testCountTipoQuestaos() {
        Assert.assertNotNull("Data on demand for 'TipoQuestao' failed to initialize correctly", dod.getRandomTipoQuestao());
        long count = TipoQuestao.countTipoQuestaos();
        Assert.assertTrue("Counter for 'TipoQuestao' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TipoQuestaoIntegrationTest.testFindTipoQuestao() {
        TipoQuestao obj = dod.getRandomTipoQuestao();
        Assert.assertNotNull("Data on demand for 'TipoQuestao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TipoQuestao' failed to provide an identifier", id);
        obj = TipoQuestao.findTipoQuestao(id);
        Assert.assertNotNull("Find method for 'TipoQuestao' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TipoQuestao' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TipoQuestaoIntegrationTest.testFindAllTipoQuestaos() {
        Assert.assertNotNull("Data on demand for 'TipoQuestao' failed to initialize correctly", dod.getRandomTipoQuestao());
        long count = TipoQuestao.countTipoQuestaos();
        Assert.assertTrue("Too expensive to perform a find all test for 'TipoQuestao', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TipoQuestao> result = TipoQuestao.findAllTipoQuestaos();
        Assert.assertNotNull("Find all method for 'TipoQuestao' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TipoQuestao' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TipoQuestaoIntegrationTest.testFindTipoQuestaoEntries() {
        Assert.assertNotNull("Data on demand for 'TipoQuestao' failed to initialize correctly", dod.getRandomTipoQuestao());
        long count = TipoQuestao.countTipoQuestaos();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TipoQuestao> result = TipoQuestao.findTipoQuestaoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TipoQuestao' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TipoQuestao' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TipoQuestaoIntegrationTest.testFlush() {
        TipoQuestao obj = dod.getRandomTipoQuestao();
        Assert.assertNotNull("Data on demand for 'TipoQuestao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TipoQuestao' failed to provide an identifier", id);
        obj = TipoQuestao.findTipoQuestao(id);
        Assert.assertNotNull("Find method for 'TipoQuestao' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTipoQuestao(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TipoQuestao' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TipoQuestaoIntegrationTest.testMergeUpdate() {
        TipoQuestao obj = dod.getRandomTipoQuestao();
        Assert.assertNotNull("Data on demand for 'TipoQuestao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TipoQuestao' failed to provide an identifier", id);
        obj = TipoQuestao.findTipoQuestao(id);
        boolean modified =  dod.modifyTipoQuestao(obj);
        Integer currentVersion = obj.getVersion();
        TipoQuestao merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TipoQuestao' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TipoQuestaoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TipoQuestao' failed to initialize correctly", dod.getRandomTipoQuestao());
        TipoQuestao obj = dod.getNewTransientTipoQuestao(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TipoQuestao' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TipoQuestao' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'TipoQuestao' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TipoQuestaoIntegrationTest.testRemove() {
        TipoQuestao obj = dod.getRandomTipoQuestao();
        Assert.assertNotNull("Data on demand for 'TipoQuestao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TipoQuestao' failed to provide an identifier", id);
        obj = TipoQuestao.findTipoQuestao(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TipoQuestao' with identifier '" + id + "'", TipoQuestao.findTipoQuestao(id));
    }
    
}
