// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.ufpb.dce.bloomer.core.model;

import br.ufpb.dce.bloomer.core.model.TipoJogoIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TipoJogoIntegrationTest_Roo_Configurable {
    
    declare @type: TipoJogoIntegrationTest: @Configurable;
    
}
